import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { motion } from "framer-motion";
import { ArrowRight, ArrowUpRight, Check, Linkedin, Mail, MapPin, Menu, Phone, Quote, Sparkles, X } from "lucide-react";
import { Link } from "react-router-dom";

const team = [
  { name: "Maya Richardson", role: "Chief Executive Officer", bio: "A strategic builder focused on people, partnerships and long-term impact.", image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=700&q=85" },
  { name: "Daniel Kim", role: "Engineering Manager", bio: "Leads our technical practice with a passion for rigorous, elegant solutions.", image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=700&q=85" },
  { name: "Priya Nair", role: "Project Head", bio: "Turns ambitious briefs into calm, coordinated and measurable delivery.", image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=700&q=85" },
  { name: "Ethan Brooks", role: "Survey & CAD Director", bio: "Combines field intelligence and digital craft to make every line count.", image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=85" },
];

const fadeUp = { initial: { opacity: 0, y: 26 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.15 }, transition: { duration: 0.65 } };

export default function About() {
  return <div className="min-h-screen overflow-x-hidden bg-[#f8fafc] text-slate-900">
    <Navbar />
    <main>
      <section className="relative isolate overflow-hidden bg-slate-950 pb-28 pt-44 text-white"><div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=2200&q=90')] bg-cover bg-center opacity-45"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/75 to-slate-950/30"/><div className="relative mx-auto max-w-7xl px-5 lg:px-8"><motion.div {...fadeUp} className="max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-bold tracking-widest backdrop-blur"><Sparkles size={14} className="text-amber-300"/> THE NOVABUILD STORY</div><h1 className="font-display text-5xl font-semibold leading-[1.06] tracking-[-.05em] sm:text-7xl">We make complex<br/><span className="text-teal-300">feel possible.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">NovaBuild is an independent engineering, surveying and construction partner for people shaping the places where the world lives, works and connects.</p></motion.div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><div className="grid items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><motion.div {...fadeUp}><p className="eyebrow">WHO WE ARE</p><h2 className="section-title mt-4">Built for the details that make a difference.</h2><p className="body-copy mt-6">Since our beginning, NovaBuild has helped ambitious teams turn early ideas into enduring places. We sit at the intersection of engineering precision, digital craft and human understanding.</p><p className="body-copy mt-4">Our specialists work across civil engineering drafting, survey mapping, land surveying, project management and design. That breadth means fewer handoffs, clearer decisions and better momentum for every project.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Independent thinking", "Measured delivery", "Global perspective", "Human partnership"].map(x => <div key={x} className="flex items-center gap-3 text-sm font-bold"><span className="grid h-6 w-6 place-items-center rounded-full bg-teal-100 text-teal-700"><Check size={14}/></span>{x}</div>)}</div></motion.div><motion.div {...fadeUp} className="relative"><img src="https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1300&q=85" alt="NovaBuild architectural project" className="h-[520px] w-full rounded-[2rem] object-cover shadow-2xl"/><div className="absolute -bottom-7 -left-4 max-w-[245px] rounded-2xl bg-teal-700 p-6 text-white shadow-xl sm:-left-8"><p className="font-display text-4xl font-semibold">15+</p><p className="mt-1 text-sm text-teal-100">years of turning plans into progress</p></div></motion.div></div></section>
      <section className="bg-white py-24 lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><motion.div {...fadeUp} className="max-w-2xl"><p className="eyebrow">OUR PRINCIPLES</p><h2 className="section-title mt-4">Good work is felt long after it is finished.</h2></motion.div><div className="mt-14 grid gap-5 md:grid-cols-3"><motion.div {...fadeUp} className="rounded-3xl bg-slate-900 p-8 text-white"><p className="text-5xl font-display text-teal-300">01</p><h3 className="mt-16 text-xl font-bold">Clarity over noise</h3><p className="mt-3 text-sm leading-6 text-slate-400">We communicate early, often and honestly so the right decisions stay visible.</p></motion.div><motion.div {...fadeUp} transition={{delay:.1}} className="rounded-3xl bg-teal-50 p-8"><p className="text-5xl font-display text-teal-700">02</p><h3 className="mt-16 text-xl font-bold">Craft with purpose</h3><p className="mt-3 text-sm leading-6 text-slate-500">Every drawing, measurement and milestone has a reason to exist.</p></motion.div><motion.div {...fadeUp} transition={{delay:.2}} className="rounded-3xl bg-amber-50 p-8"><p className="text-5xl font-display text-amber-600">03</p><h3 className="mt-16 text-xl font-bold">Better together</h3><p className="mt-3 text-sm leading-6 text-slate-500">The strongest outcomes come from close collaboration and shared ownership.</p></motion.div></div></div></section>
      <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><motion.div {...fadeUp} className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">THE PEOPLE OF NOVABUILD</p><h2 className="section-title mt-4">Experienced minds.<br/>Open collaborators.</h2></div><p className="body-copy max-w-sm">A multidisciplinary team united by curiosity, care and a high standard for the built world.</p></motion.div><div className="mt-14 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{team.map((member, i) => <motion.article key={member.name} {...fadeUp} transition={{delay:i*.08}}><div className="group relative overflow-hidden rounded-[2rem] bg-slate-100"><img src={member.image} alt={member.name} className="aspect-[.9] w-full object-cover grayscale transition duration-500 group-hover:scale-105 group-hover:grayscale-0"/><Link to="/#contact" className="absolute bottom-4 right-4 grid h-10 w-10 place-items-center rounded-full bg-white text-teal-700 shadow-lg transition hover:bg-teal-600 hover:text-white"><Linkedin size={16}/></Link></div><h3 className="mt-5 text-lg font-bold">{member.name}</h3><p className="mt-1 text-xs font-bold uppercase tracking-wider text-teal-700">{member.role}</p><p className="mt-3 text-sm leading-6 text-slate-500">{member.bio}</p></motion.article>)}</div></section>
      <section className="bg-teal-700 py-20 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 sm:grid-cols-[1fr_auto] sm:items-center lg:px-8"><div><p className="eyebrow text-teal-200">READY TO MOVE FORWARD?</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-tight sm:text-5xl">Let’s shape what’s next.</h2></div><Link to="/#contact" className="inline-flex w-fit items-center rounded-full bg-white px-6 py-3.5 text-sm font-bold text-teal-800 transition hover:-translate-y-1">Start a conversation <ArrowRight className="ml-2" size={17}/></Link></div></section>
    </main>
    <Footer />
  </div>;
}
