import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { motion } from "framer-motion";
import { ArrowRight, Check, ChevronRight, Compass, DraftingCompass, Layers3, MapPin, Building2, ClipboardCheck } from "lucide-react";
import { Link } from "react-router-dom";

const serviceDetails = [
  { icon: DraftingCompass, number: "01", title: "Civil Engineering Drafting", text: "From early concepts to construction-ready documents, our drafting specialists turn engineering intent into accurate, coordinated deliverables.", bullets: ["Construction documentation", "Civil 3D surfaces and grading", "As-built and redline updates"] },
  { icon: Compass, number: "02", title: "Survey Mapping", text: "We make site intelligence clear and usable with mapping workflows that connect field data to confident project decisions.", bullets: ["Topographic mapping", "GIS data preparation", "Digital terrain models"] },
  { icon: MapPin, number: "03", title: "Land Surveying", text: "Dependable field-to-finish support for boundaries, infrastructure and the details that make a site ready to build.", bullets: ["Boundary and detail surveys", "Construction staking support", "Elevation and control networks"] },
  { icon: Layers3, number: "04", title: "Interior Design", text: "Thoughtful interiors that translate brand, function and movement into spaces people want to use.", bullets: ["Space planning", "Material and finish direction", "3D visualization"] },
  { icon: Building2, number: "05", title: "Build & Contracting", text: "An integrated approach to delivery that protects quality, schedule and the original ambition of the project.", bullets: ["Pre-construction planning", "Trade coordination", "Site delivery support"] },
  { icon: ClipboardCheck, number: "06", title: "Project Management", text: "Clear ownership and calm coordination across every stage, from the first brief to final handover.", bullets: ["Scope and timeline control", "Quality assurance", "Stakeholder reporting"] },
];

const steps = ["Understand the brief", "Build the roadmap", "Create with precision", "Review and refine", "Deliver with confidence"];
const fadeUp = { initial: { opacity: 0, y: 26 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, amount: 0.15 }, transition: { duration: 0.65 } };

export default function Services() {
  return <div className="min-h-screen overflow-x-hidden bg-[#f8fafc] text-slate-900">
    <Navbar />
    <main><section className="relative overflow-hidden bg-slate-950 pb-28 pt-44 text-white"><div className="absolute inset-0 bg-[url('https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=2200&q=90')] bg-cover bg-center opacity-45"/><div className="absolute inset-0 bg-gradient-to-r from-slate-950 via-slate-950/75 to-slate-950/20"/><motion.div {...fadeUp} className="relative mx-auto max-w-7xl px-5 lg:px-8"><p className="eyebrow text-teal-300">WHAT WE DO</p><h1 className="mt-5 max-w-4xl font-display text-5xl font-semibold leading-[1.06] tracking-[-.05em] sm:text-7xl">Expertise that makes<br/><span className="text-teal-300">progress possible.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">One connected team for the technical, creative and operational work behind exceptional places.</p></motion.div></section>
      <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><motion.div {...fadeUp} className="max-w-2xl"><p className="eyebrow">OUR CAPABILITIES</p><h2 className="section-title mt-4">The right people for every line, layer and milestone.</h2><p className="body-copy mt-6">Our services are designed to work independently or as one integrated partner. Choose the specialist support you need, with the clarity and consistency of a team that sees the whole picture.</p></motion.div><div className="mt-16 grid gap-6 md:grid-cols-2">{serviceDetails.map((service, i) => { const Icon = service.icon; return <motion.article {...fadeUp} transition={{ delay: i * .06 }} key={service.title} className="group rounded-[2rem] border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:border-teal-200 hover:shadow-xl lg:p-9"><div className="flex items-start justify-between"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-teal-50 text-teal-700 transition group-hover:bg-teal-600 group-hover:text-white"><Icon size={26}/></span><span className="font-display text-3xl text-slate-200">{service.number}</span></div><h3 className="mt-8 text-2xl font-bold tracking-tight">{service.title}</h3><p className="mt-3 max-w-lg text-sm leading-7 text-slate-500">{service.text}</p><div className="mt-6 space-y-3 border-t border-slate-100 pt-5">{service.bullets.map(bullet => <div key={bullet} className="flex items-center gap-3 text-sm font-semibold"><Check size={16} className="text-teal-600"/>{bullet}</div>)}</div></motion.article>; })}</div></section>
      <section className="bg-slate-900 py-24 text-white lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-8"><motion.div {...fadeUp} className="max-w-xl"><p className="eyebrow text-teal-300">HOW WE WORK</p><h2 className="section-title mt-4 text-white">Simple steps.<br/>Serious momentum.</h2></motion.div><div className="mt-14 grid gap-4 md:grid-cols-5">{steps.map((step, i) => <motion.div {...fadeUp} transition={{ delay: i*.08 }} key={step} className="relative rounded-2xl border border-white/10 bg-white/[.04] p-6"><span className="text-sm font-bold text-amber-300">0{i+1}</span><h3 className="mt-10 text-lg font-semibold">{step}</h3>{i < steps.length - 1 && <ChevronRight className="absolute -right-3 top-1/2 hidden text-teal-300 md:block" size={20}/>}</motion.div>)}</div></div></section>
      <section className="bg-teal-700 py-20 text-white"><div className="mx-auto flex max-w-7xl flex-col gap-7 px-5 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div><p className="eyebrow text-teal-200">HAVE A PROJECT IN MIND?</p><h2 className="mt-3 font-display text-4xl font-semibold">Let’s make the next step clear.</h2></div><Link to="/#contact" className="inline-flex w-fit items-center rounded-md bg-white px-4 py-2.5 text-xs font-bold text-teal-800">Talk to our team <ArrowRight className="ml-2" size={17}/></Link></div></section></main><Footer /></div>;
}
